function n = tmvs_hash (id)

prime = uint32 (31);

n = tmvs_foldl (@(n, k) n + prime * uint32 (k), ...
  {(tmvs_getfield (id, 'source', 0)), ...
   (tmvs_getfield (id, 'quantity', 0)), ...
   (tmvs_getfield (id, 'site', 0)), ...
   (tmvs_getfield (id, 'surface', 0)), ...
   (tmvs_getfield (id, 'room', 0)), ...
   (tmvs_getfield (id, 'section', 0)), ...
   (tmvs_getfield (id, 'ordinal', 0)), ...
   (tmvs_getfield (id, 'material', 0)), ...
   (tmvs_getfield (id, 'region', 0))}, uint32 (0));

end
